### ISSUE TITLE
UI UX overhaul

### ISSUE THREAD

**Issue by ghost** [cosmostation/cosmostation-ios#148]
Hey all, I think the UI UX of this ios app has a lot of room for improvement.

- From large margins
- wildly different color schemes for each wallet (make ONE GOOD one, not MANY bad ones)
- having to whitelist a chain for your mnemonic
- Send button looks bad (make it part of the panel
- displaying 0s when unnecessary 

![IMG_91685D36D4BB-1](https://user-images.githubusercontent.com/95767439/199557695-b33010ae-c699-41f3-b7f3-4bb01941e461.jpeg )

- Token Icons are too visually busy (small screens makes it look overly complex with stripped circular borders)

![IMG_840B47593A9F-1](https://user-images.githubusercontent.com/95767439/199557877-d9fd7add-21f5-41f2-bc94-559dd56ddee8.jpeg)

We should try and make the UI UX closer to the web extension which actually has good UI UX:

ONE MNEUMONIC displays ALL of your assets not having to senselessly switch around
<img width="349" alt="Screen Shot 2022-11-02 at 11 21 43" src="https://user-images.githubusercontent.com/95767439/199558375-7c215770-66c4-414e-96b2-7774d5d18115.png">

**Comment by professionallyatortoise** [comment]
Can we spin up a doc or something where we can collaborate on a new UI UX?

**Comment by wannabit-yongjoo** [comment]
@hyeryeong-lim

**Comment by hyeryeong-lim** [comment]
@professionallyatortoise 
Thank you for your valuable feedback. We will refer to your opinions when renewing UI/UX in the future.
Creating documents for collaboration also requires internal review. Thank you.

**Comment by professionallyatortoise** [comment]
Thank you for the response @hyeryeong-lim , I am happy to help in both implementation and design reach out if you would like my help

**Comment by albertopeam** [comment]
@professionallyatortoise, maybe instead of a complete redesign we can make small improvements to UI/UX, like:
1.  make all the buttons tappable
2. make the cells clickable
3. render html instead of plain text(vote detail, maybe other places)
4. create UI components to avoid code repetition
5. long click on back button doesn't show full navigation paths
and probably more that I haven't found. 

As far as I know cosmostation has accepted all the UI changes that I have sent to them so, I encourage you to make small changes that make the app better

**Comment by professionallyatortoise** [comment]
they have rejected one of my UI changes: https://github.com/cosmostation/cosmostation-ios/pull/108
@albertopeam 
@hyeryeong-lim 
@wannabit-yongjoo 

But moreover, the UI is very clunky, it seems like there should be consensus on a vision for the UI because like what happened to my PR, the effort was put in to get up to speed with the prj only to be rejected. Guiding principals or something. 

Behavior like having to choose which networks to agree to use your mnemonic, then when you want to use a network you forgot to add you need to do like a 5-step workflow in the settings menu. It's like...really bad design.

Showing only 1 network asset's at once...really poor design. It makes managing your assets means you need to navigate a million places. 

Unique color pallets per network make the UI feel like 2001 myspace where everyone made poor websites in an effort to be different rather than good. 

A figma or something would give devs who want to contribute something more substantial to work off of because it's frankly a mess right now. 

A mandate like: "Let's move it closer to the cosmostation chrome extension" would be really productive in my opinion. 
- shows all assets per mnemonic/wallet
- not messing around with custom themes: make one good one
- networks only need a simple toggle to be added not 5 step workflow 
- Icons are standard token icons, not this weird striped bezels thing 

I can make these changes, but if my PRs are being rejected then you see my point

**Comment by professionallyatortoise** [comment]
![IMG_9DF2DF3C0B13-1](https://user-images.githubusercontent.com/95767439/200126162-067f36e6-79be-4f7a-b9ca-876af42e71bf.jpeg)

This is a good example of too much going on, stripped bezel icons, and overly colorful network text. Simple is better. Also a period, in the end, doesn't make sense in the title of the UI card.

**Comment by professionallyatortoise** [comment]
Okay, I need names, who is obsessed with stripped bezel icons?? Haha it's wayyyy toooo busy. These are small screens people are working on, good icon selection means choosing things with lowest amount of lines etc,

<img width="793" alt="Screen Shot 2022-11-05 at 09 12 15" src="https://user-images.githubusercontent.com/95767439/200126751-123c54d7-aa92-4592-b435-7ffe4539f1fb.png">

Strange color selection on the next button, some buttons have transparent bg and others are solid...like the UI is just so painful to look at I'm sorry if this is ranting and not productive. I just feel like it has to be said. 
![image](https://user-images.githubusercontent.com/95767439/200126898-8ed290f2-865c-4395-8b75-379407d34750.png)

**Comment by professionallyatortoise** [comment]
It is painfully obvious that insufficient consideration has been given to the UI/UX

**Comment by albertopeam** [comment]
Hi!

Regarding the PR that was rejected: Both sides are reasonable, you want to improve the UI but they want consistency. I think is needed a design with a roadmap as you said @professionallyatortoise. So It depends on the owners of the repo to consider accept a new redesign if someone from outside creates it or if they want to share the design roadmap if it exists :) @wannabit-yongjoo @hyeryeong-lim

**Comment by professionallyatortoise** [comment]
I think @albertopeam suggestion on the resume is a step in the right direction! If we want to modernize the app, because it looks like it's from 2006, a UX roadmap would be great so we're all moving in the same direction.

**Comment by albertopeam** [comment]
we need your thoughts  @wannabit-yongjoo @hyeryeong-lim to understand if you are open that others introduce this new feature

**Comment by hyeryeong-lim** [comment]
Thank you for providing valuable feedback on the UI/UX of the Cosmostation mobile.
The design team is currently aware of the feedback that you provided and we are trying our best to reflect the opinions.
We are planning on renewing the UI/UX of the mobile wallet and your feedback will be reflected. 
Please note that the Cosmostation extension wallet is how the design team would like to provide the UI/UX in the future.
Our team is always trying our best to provide the best services and thank you again for your valuable feedback. @professionallyatortoise @albertopeam

**Comment by professionallyatortoise** [comment]
@hyeryeong-lim that sounds awesome! I would love to see a world where the extension and the mobile apps have more consistent UI/UXs. 

Please make sure you are consulting UI UX PEOPLE and not just developers when implementing because half of this app would not pass QA if there was even one UI/UX person approving it. It has to be said.

**Comment by albertopeam** [comment]
Based on your response @hyeryeong-lim I extract that we are not allowed to introduce a new feature in the wallet. If I understand it wrong let me know. :(
